name: musical
main: io.github.dolphin2410.mc.plugin.MusicalChairPlugin
version: 0.0.1
api-version: 1.17
author: dolphin2410
libraries:
  - io.github.monun:kommand:2.6.6
  - io.github.teamcheeze:plum:0.0.13
